site_name: Elasticsearch Containerization Guide
use_directory_urls: true
theme:
  name: material
  logo: elastic_logo.svg
  palette:
    scheme: slate
    primary: yellow
    accent: yellow
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer

repo_url: https://github.com/Snehal-Pradhan/elasticsearch-containerization-guide
repo_name: elasticsearch-containerization-guide
repo_type: github

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Getting Started: gettingStarted.md

extra_css:
  - css/footer.css
  - css/header.css
  - css/body.css
